apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: java
  namespace: petclinic
spec:
  tags:
    - name: openjdk-17-ubi9
      from:
        kind: ImageStreamTag
        name: java:openjdk-17-ubi9
        namespace: openshift
    - name: latest
      from:
        kind: ImageStreamTag
        name: java:openjdk-17-ubi9
