apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: petclinic-scc
allowPrivilegedContainer: false
allowPrivilegeEscalation: false
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:petclinic:default
  - system:serviceaccount:petclinic:builder
  - system:authenticated
groups:
  - system:cluster-admins
